# Generated by Django 5.2.6 on 2025-09-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_pic',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
